// Interop test: TypeScript SDK <-> Rust krymux-tunnel binary
// (../../target/release/krymux-tunnel.exe, override with ECTUN_BIN).
//
// Phase A: Rust server + TS client (identities generated by the TS SDK, so the
//          Rust side must accept our Ed25519 certs/fingerprints) — echo 1 MiB
//          byte-exact for each compression mode, deny unrouted targets, reject
//          a non-whitelisted Rust-generated key.
// Phase B: TS server + Rust client driven through a SOCKS5 frontend — echo
//          1 MiB byte-exact for each compression mode.
//
// Patterns follow ../../interop/test-interop.mjs; waits are readiness polls,
// not fixed sleeps.
//
//   npx tsx scripts/interop-with-rust.ts

import { spawn, type ChildProcess } from 'node:child_process';
import * as net from 'node:net';
import * as crypto from 'node:crypto';
import { Buffer } from 'node:buffer';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as assert from 'node:assert/strict';
import {
  EctunClient, createProxyServer, generateIdentity, loadIdentity, saveIdentity, noopLogger,
} from '../src/index.js';
import type { TunnelStream } from '../src/index.js';

// Rust binary: ECTUN_BIN env var, or the release build at the repo root
// (ectun-rs/target/release/krymux-tunnel.exe — three levels up from scripts/).
const RS = process.env.ECTUN_BIN
  ?? fileURLToPath(new URL('../../../target/release/krymux-tunnel.exe', import.meta.url));
const KEYDIR = mkdtempSync(join(tmpdir(), 'krymux-ts-interop-'));
mkdirSync(KEYDIR, { recursive: true });

const PASS: string[] = [];
const FAIL: string[] = [];
function report(name: string, err?: unknown): void {
  if (err) {
    FAIL.push(name);
    console.error(`FAIL ${name}: ${err instanceof Error ? err.message : String(err)}`);
  } else {
    PASS.push(name);
    console.log(`ok   ${name}`);
  }
}

const tmpJson = (p: string, o: unknown) => writeFileSync(p, JSON.stringify(o, null, 2));

// ---------- process / network helpers (event-driven, no fixed sleeps) ----------

type Spawned = { proc: ChildProcess; stderr: string };

function start(cmd: string, args: string[]): Promise<Spawned> {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let stderr = '';
    proc.stderr?.on('data', (c: Buffer) => {
      stderr += c.toString();
    });
    proc.stdout?.on('data', () => {});
    proc.once('error', reject);
    proc.once('spawn', () => resolve({ proc, stderr }));
  });
}

function runToExit(cmd: string, args: string[], timeoutMs = 15000): Promise<string> {
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let out = '';
    const t = setTimeout(() => {
      p.kill();
      reject(new Error(`timeout: ${cmd} ${args.join(' ')}`));
    }, timeoutMs);
    p.stdout?.on('data', (c: Buffer) => {
      out += c.toString();
    });
    p.stderr?.on('data', (c: Buffer) => {
      out += c.toString();
    });
    p.once('error', (e) => {
      clearTimeout(t);
      reject(e);
    });
    p.once('exit', () => {
      clearTimeout(t);
      resolve(out);
    });
  });
}

/** Rust `keygen`: writes <name>.key.pem/<name>.crt.pem, prints the fingerprint. */
async function keygen(args: string[]): Promise<string> {
  const out = await runToExit(RS, ['keygen', ...args]);
  const m = out.match(/fingerprint: (sha256:[0-9a-f]{64})/);
  if (!m) throw new Error('keygen failed: ' + out);
  return m[1]!;
}

function waitExit(proc: ChildProcess, timeoutMs = 8000): Promise<void> {
  return new Promise((resolve, reject) => {
    if (proc.exitCode !== null) return resolve();
    const t = setTimeout(() => reject(new Error('process did not exit')), timeoutMs);
    proc.once('exit', () => {
      clearTimeout(t);
      resolve();
    });
  });
}

/** Poll until a TCP port accepts connections (readiness probe). */
function waitTcp(host: string, port: number, timeoutMs = 10000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  return new Promise((resolve, reject) => {
    const attempt = () => {
      const sock = net.connect({ host, port });
      sock.once('connect', () => {
        sock.destroy();
        resolve();
      });
      sock.once('error', () => {
        sock.destroy();
        if (Date.now() > deadline) reject(new Error(`port never opened: ${host}:${port}`));
        else setTimeout(attempt, 60);
      });
    };
    attempt();
  });
}

function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const srv = net.createServer();
    srv.listen(0, '127.0.0.1', () => {
      const port = (srv.address() as net.AddressInfo).port;
      srv.close(() => resolve(port));
    });
    srv.once('error', reject);
  });
}

function startEcho(): Promise<{ srv: net.Server; port: number }> {
  const srv = net.createServer((s) => s.pipe(s));
  return new Promise((r) => srv.listen(0, '127.0.0.1', () => r({ srv, port: (srv.address() as net.AddressInfo).port })));
}

async function readAll(stream: TunnelStream): Promise<Buffer> {
  const parts: Buffer[] = [];
  for await (const c of stream) parts.push(c as Buffer);
  return Buffer.concat(parts);
}

/** Exactly 1 MiB: half random (incompressible), half repeating (compressible). */
function payload1MiB(): Buffer {
  const half = 512 * 1024;
  const pattern = Buffer.from('krymux-ts-interop-payload ');
  const reps = Math.ceil(half / pattern.length);
  const compressible = Buffer.concat(Array(reps).fill(pattern)).subarray(0, half);
  return Buffer.concat([crypto.randomBytes(half), compressible]);
}

// ---------- SOCKS5 client (drives the Rust client's frontend) ----------

function once(ev: net.Socket, name: string): Promise<void> {
  return new Promise((r) => ev.once(name, r));
}

async function readN(sock: net.Socket, n: number): Promise<Buffer> {
  return new Promise((resolve) => {
    const chunks: Buffer[] = [];
    const onData = (c: Buffer) => {
      chunks.push(c);
      if (Buffer.concat(chunks).length >= n) {
        sock.off('data', onData);
        resolve(Buffer.concat(chunks).subarray(0, n));
      }
    };
    sock.on('data', onData);
  });
}

async function socks5Echo(proxyHost: string, proxyPort: number, host: string, port: number, payload: Buffer): Promise<Buffer> {
  const sock = net.connect({ host: proxyHost, port: proxyPort });
  await once(sock, 'connect');
  sock.write(Buffer.from([5, 1, 0]));
  await readN(sock, 2);
  const h = Buffer.from(host);
  sock.write(Buffer.from([5, 1, 0, 3, h.length, ...h, port >> 8, port & 0xff]));
  const rep = await readN(sock, 10);
  if (rep[1] !== 0) throw new Error('socks5 reply ' + rep[1]);
  sock.write(payload);
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let got = 0;
    sock.on('data', (c: Buffer) => {
      chunks.push(c);
      got += c.length;
      if (got >= payload.length) {
        sock.destroy();
        resolve(Buffer.concat(chunks));
      }
    });
    sock.once('error', reject);
    sock.once('close', () => resolve(Buffer.concat(chunks)));
  });
}

// global watchdog: never hang the CI
setTimeout(() => {
  console.error('interop: GLOBAL TIMEOUT');
  process.exit(2);
}, 180_000);

// ================= Phase A: Rust server + TS client =================
{
  const procs: ChildProcess[] = [];
  const echo = await startEcho();
  const tunnelPort = await freePort();
  let client: EctunClient | null = null;

  try {
    // identities generated by the TS SDK; the Rust side must load our PEMs
    // and accept our fingerprints byte-for-byte
    const serverId = generateIdentity({ cn: 'interop-ts-server' });
    saveIdentity(KEYDIR, serverId, { name: 'server' });
    const aliceId = generateIdentity({ cn: 'interop-ts-alice' });
    saveIdentity(KEYDIR, aliceId, { name: 'alice' });
    // rust-generated identity, NOT in the whitelist
    await keygen(['--out', KEYDIR, '--role', 'client', '--name', 'mallory']);

    tmpJson(join(KEYDIR, 'server.json'), {
      listen: `127.0.0.1:${tunnelPort}`,
      identity: { key: join(KEYDIR, 'server.key.pem'), cert: join(KEYDIR, 'server.crt.pem') },
      auth: { mode: 'whitelist', fingerprints: [aliceId.fingerprint] },
      routes: [
        { host: ['echo'], upstream: ['127.0.0.1', echo.port] },
      ],
      clientTargets: { enabled: false },
    });
    const rsServer = (await start(RS, ['server', '--config', join(KEYDIR, 'server.json')])).proc;
    procs.push(rsServer);
    await waitTcp('127.0.0.1', tunnelPort);

    // TS client with TS-generated identity, loaded back from disk
    const alice = loadIdentity({ key: join(KEYDIR, 'alice.key.pem'), cert: join(KEYDIR, 'alice.crt.pem') });
    assert.equal(alice.fingerprint, aliceId.fingerprint, 'loadIdentity fingerprint round-trip');
    client = await EctunClient.connect({
      endpoint: `127.0.0.1:${tunnelPort}`,
      identity: alice,
      serverFingerprint: serverId.fingerprint,
    });

    // 1 MiB echo per compression mode, byte-exact
    for (const algo of ['none', 'deflate', 'auto']) {
      try {
        const payload = payload1MiB();
        const s = await client.openStream({ host: 'echo', port: 9, compression: algo });
        s.write(payload);
        s.end();
        const out = await readAll(s);
        assert.equal(out.length, payload.length, 'length');
        assert.ok(out.equals(payload), 'bytes');
        report(`A: echo ${algo} 1MiB byte-exact (ts client -> rust server)`);
      } catch (e) {
        report(`A: echo ${algo}`, e);
      }
    }

    // unrouted target denied
    try {
      await assert.rejects(
        () => client!.openStream({ host: 'nope.example', port: 80 }),
        (e: Error) => /no route|denied/i.test(e.message),
      );
      report('A: unrouted target denied');
    } catch (e) {
      report('A: deny', e);
    }

    // non-whitelisted key rejected (rust-generated mallory, fail-closed)
    try {
      const mallory = loadIdentity({ key: join(KEYDIR, 'mallory.key.pem'), cert: join(KEYDIR, 'mallory.crt.pem') });
      await assert.rejects(
        () => EctunClient.connect({
          endpoint: `127.0.0.1:${tunnelPort}`,
          identity: mallory,
          serverFingerprint: serverId.fingerprint,
        }),
        (e: Error) => /handshake|certificate|socket|ECONNRESET|closed|verification/i.test(e.message),
      );
      report('A: non-whitelisted key rejected');
    } catch (e) {
      report('A: whitelist reject', e);
    }
  } catch (e) {
    report('A: setup', e);
  } finally {
    client?.close('phase-a done');
    for (const p of procs) p.kill();
    await Promise.allSettled(procs.map((p) => waitExit(p)));
    echo.srv.close();
  }
}

// ================= Phase B: TS server + Rust client (socks5) =================
{
  const echo = await startEcho();
  let tsServer: ReturnType<typeof createProxyServer> | null = null;
  const procs: ChildProcess[] = [];
  try {
    const serverId = generateIdentity({ cn: 'interop-ts-server-b' });
    const bobFp = await keygen(['--out', KEYDIR, '--role', 'client', '--name', 'bob']);

    tsServer = createProxyServer({
      listen: '127.0.0.1:0',
      identity: serverId,
      auth: { mode: 'whitelist', fingerprints: [bobFp] },
      routes: [{ host: '*', upstream: { host: '127.0.0.1', port: echo.port } }],
      log: noopLogger(),
    });
    await tsServer.start();
    const tunnelPort = (tsServer.address() as net.AddressInfo).port;

    for (const comp of ['none', 'deflate', 'auto']) {
      const socksPort = await freePort();
      tmpJson(join(KEYDIR, 'rs-client.json'), {
        endpoint: `127.0.0.1:${tunnelPort}`,
        identity: { key: join(KEYDIR, 'bob.key.pem'), cert: join(KEYDIR, 'bob.crt.pem') },
        serverFingerprint: serverId.fingerprint,
        socks5: `127.0.0.1:${socksPort}`,
        compression: comp,
      });
      const rsClient = (await start(RS, ['client', '--config', join(KEYDIR, 'rs-client.json')])).proc;
      procs.push(rsClient);
      await waitTcp('127.0.0.1', socksPort, 10000);
      try {
        const payload = payload1MiB();
        const out = await socks5Echo('127.0.0.1', socksPort, 'echo.x', 9, payload);
        assert.equal(out.length, payload.length, 'length');
        assert.ok(out.equals(payload), 'bytes');
        report(`B: rust client (${comp}) -> ts server, 1MiB echo via socks5`);
      } catch (e) {
        report(`B: ${comp}`, e);
      }
      rsClient.kill();
      await waitExit(rsClient);
    }
  } catch (e) {
    report('B: setup', e);
  } finally {
    for (const p of procs) p.kill();
    await Promise.allSettled(procs.map((p) => waitExit(p)));
    await tsServer?.stop();
    echo.srv.close();
  }
}

console.log(`\ninterop: ${PASS.length} passed, ${FAIL.length} failed`);
try {
  rmSync(KEYDIR, { recursive: true, force: true });
} catch {
  /* best effort on Windows */
}
process.exit(FAIL.length ? 1 : 0);
